---
title: "data-munging"
author: "Heike Hofmann"
date: "March 3, 2016"
output: html_document
---

```{r, echo=FALSE}
census1870 <- read.csv("data/states-1870.csv", stringsAsFactors = FALSE)
foreigners <- census1870[, c("FOREIGN.BORN.PERSONS", "NATIVE.BORN.PERSONS", "TOTAL.FEMALES", "TOTAL.MALES", "TOTAL.POPULATION")]

# sanity check:
summary(with(foreigners, FOREIGN.BORN.PERSONS+NATIVE.BORN.PERSONS==TOTAL.POPULATION))
summary(with(foreigners, TOTAL.FEMALES+TOTAL.MALES==TOTAL.POPULATION))

```

```{r, echo=FALSE}
blindprop <- read.csv("data/blind-per.state.csv", na.strings="#VALUE!")
library(ggplot2)
#qplot(reorder(State,  Female.blind.perc), Female.blind.perc, data=blindprop) + coord_flip()

library(tidyr)
library(dplyr)
blind <- blindprop %>% select(State, Male.native.blind.perc, Male.foreign.blind.perc, Female.native.blind.perc, Female.foreign.blind.perc) %>% gather(gender.born, blind, -State)
blind$blind <- as.numeric(blind$blind)

blind$gender <- "Male"
blind$gender[grep("Female", blind$gender.born)] <- "Female"

blind$nativity <- "Foreign"
blind$nativity[grep("native", blind$gender.born)] <- "Native"

library(RColorBrewer)
cols <- brewer.pal(n=8, name="Paired")

blind$gender.born <- with(blind, interaction(gender, nativity, sep="/"))
blind$gender.born <- factor(blind$gender.born, levels=c("Female/Native", "Female/Foreign", "Male/Foreign", "Male/Native"))
blind$State <- reorder(blind$State, blind$blind, function(x) x[1]+x[3])

ggplot(data=data.frame(blind), aes(x=State, weight=blind, fill=gender.born)) +
  geom_bar() + 
  coord_flip() + 
  scale_fill_manual("Gender/Nativity", values=cols[c(6,5,1,2)]) +
  theme(legend.position="bottom") + 
  ylab("Percentage") 
```


```{r}
# founding years of states
url <- "https://en.wikipedia.org/wiki/List_of_U.S._states_by_date_of_admission_to_the_Union"

library(rvest)
html <- read_html(url)
tabs <- html %>%  html_nodes("table") 
founding <- html_table(tabs[[1]], fill=TRUE)

library(lubridate)
founding$date <- ymd(gsub("00000000(....-..-..)-0000.*","\\1", founding$`Date of admission`))
founding$STATE <- trimws(toupper(substr(founding$State,6,nchar(founding$State))))

blind2 <- merge(blind, founding[,c("STATE","date")], by.x="State", by.y="STATE", all.x=TRUE)

# blind2$State <- reorder(blind2$State, blind2$date, min)
ggplot(data=blind2, aes(x=State, weight=blind, fill=gender.born)) +
  geom_bar() + 
  coord_flip() + 
  scale_fill_manual("Gender/Nativity", values=cols[c(6,5,1,2)]) +
  theme(legend.position="bottom")

```

```{r}
library(readr)
cmdr <- read_fwf("data/usa_00009.sps.txt", skip = 7, 
                fwf_positions(c(3, 14), c(11, 19)), n_max=27)
cmdr$X2 <- gsub(" \\(.\\)","",cmdr$X2)
splits <- strsplit(cmdr$X2, split="-")
splits <- plyr::ldply(splits, function(x) x)
cmdr <- data.frame(cmdr[,-2], splits)
names(cmdr) <- c("variable", "start", "stop")
cmdr$start <- as.numeric(cmdr$start)
cmdr$stop <- as.numeric(cmdr$stop)

census <- read_fwf("data/usa_00009.dat", 
                   fwf_positions(cmdr$start, cmdr$stop))
names(census) <- cmdr$variable

library(dplyr)
census %>% group_by(YEAR, SEX) %>% summarize(propBLIND=sum(BLIND==2)/n()*100, n=sum(BLIND==2), N=n())

census$PERWT <- as.numeric(census$PERWT)
census$AGE <- as.numeric(census$AGE)
census$AGE[census$AGE==999] <- NA
#write.csv(subset(census, YEAR==1870),"data/ipums-1870.csv", row.names=FALSE)

library(ggplot2)
ggplot() + geom_histogram(aes(AGE, fill=factor(BLIND)), binwidth=1,  data=census, position="dodge") + facet_grid(BLIND~YEAR, scales="free_y")
  

# this conversion takes pretty long  
states <- read_fwf("data/usa_00009.sps.txt", skip = 98, 
                fwf_positions(c(5, 10), c(7, 30)), n_max=55)
names(states) <- c("STATEICP", "State")  
states$State <- gsub("\"", "", states$State)
statelookup <- states$State
names(statelookup) <- as.numeric(states$STATEICP)
census$STATEICP <- statelookup[as.character(census$STATEICP)]

#urban
table(census$URBAN)
census$URBAN <- c(NA, "Rural", "Urban")[census$URBAN+1]

census$SEX <- c("Male", "Female")[census$SEX]

census$AGE <- as.numeric(census$AGE)

census$RACE <- c("White", "Black", "American Indian or Alaska Native", "Chinese", "Japanese", "Other Asian or Pacific Islander", "Other race", "Two major races", "Three or more major races")[census$RACE]

census$NATIVITY <- c(NA, 
                     "Native born, both parents native born",
                     "Native born, father foreign, mother native",
                     "Native born, father native, mother foreign",
                     "Native born, both parents foreign born",
                     "Foreign born")[as.numeric(census$NATIVITY)+1]


census$BLIND <- c(NA, "No", "Yes", "Illegible", "Unknown")[as.numeric(census$BLIND)+1]
stateprop <- census %>% group_by(STATEICP, SEX) %>% summarize(
  n=length(BLIND), 
  BLINDperc=100.0*sum(BLIND=="Yes")/length(BLIND),
  BLINDup=100.0*(sum(BLIND=="Yes")+1)/length(BLIND),
  BLINDdown=100.0*(sum(BLIND=="Yes")-1)/length(BLIND),
  BLIND = sum(BLIND=="Yes")
  )

qplot(reorder(STATEICP, BLIND), BLIND, data=stateprop, colour=SEX) + coord_flip()
qplot(reorder(STATEICP, BLINDperc), BLINDperc, data=stateprop, colour=SEX) +
  geom_segment(aes(y=BLINDdown, yend=BLINDup, xend=STATEICP)) +
  coord_flip() + ylim(c(-1,2.5))


circles <- read.csv("data/diameters.csv")
circles <- circles %>% group_by(state) %>% mutate(State = na.omit(State)[1])
circles$area <- (circles$pixel_diameter/2)^2*pi
# write.csv(circles, file="data/diameters.csv", row.names=FALSE)
# the areas of states' circles sort of add up to the area of the US. 

base <- subset(circles, State=="US") # this is all the blind in the US in 1870
blindprop <- read.csv("data/blind-per.state.csv", na.strings="#VALUE!")
ipums <- read.csv("data/ipums-1870.csv")

ipums %>% group_by(YEAR, BLIND) %>% summarize(n = n()) # we need to compare this to the weighted data

ipums %>% group_by(YEAR, BLIND) %>% summarize(n = n()/nrow(ipums)*38155505, slwt = sum(SLWT*1.0)/100)

# how many blind individuals were there in total in 1870? - I don't seem to be able to find a good number. 
# https://www.census.gov/newsroom/releases/archives/facts_for_features_special_editions/cb09-ff13.html

# there are 252 blind individuals in the data. This would mean that there were about 21686.26 blind individuals in the US in 1870. 
252/nrow(ipums)*38155505

# maybe better estimate: 
(blindUS <- sum(subset(ipums, BLIND=="Yes")$SLWT*1.0)/100)

# the real size diameter of the US on the chart is therefore about 2.40 inches, if 1 square inch corresponds to 4,800 individuals
sqi <- blindUS/4800
sqrt(sqi/pi)*2

#base$blindEst <- 21686.26
base$blindEst <- blindUS
#multiplier <- 21686.26/385945.4
multiplier <- blindUS/385945.4

circles$blindEst <- with(circles, area*multiplier)


# blindByState <- ipums %>% group_by(STATEICP) %>% summarize(
#   blindIPUMS = sum(BLIND=="Yes")/nrow(ipums)*38155505,
#   StateTotalIPUMS=n()/nrow(ipums)*38155505
# )

blindByState <- ipums %>% group_by(STATEICP, BLIND) %>% summarize(
  blindIPUMS = sum(SLWT)/100
)

blindByState <- blindByState %>% group_by(STATEICP) %>% mutate(
  StateTotalIPUMS = sum(blindIPUMS)/100
) %>% filter(BLIND=="Yes") %>% select(STATEICP, blindIPUMS, StateTotalIPUMS)


circles <- merge(circles, blindByState, by.x="State", by.y="STATEICP", all=TRUE)
circles$blindIPUMS[circles$location=="4I"] <- NA
circles$StateTotalIPUMS[circles$location=="4I"] <- NA
#write.csv(circles, file="data/diameters.csv", row.names=FALSE)

# state_pop <- merge(state_pop, state_blind[, c("state", "blindEst")], by="state", all.x=TRUE)
# write.csv(state_pop, file="states-1870.csv", row.names=FALSE)


# the IPUMS based estimates are pretty bad:

# generally they increase with population (which is to be expected)
qplot(abs(blindIPUMS-blindEst), y=reorder(State, area), data=circles)

# we are more interested in the relative errors. Using blindEst as a reference, we see that with a decrease in the population size, the relative error increases. 
qplot(abs(blindIPUMS-blindEst)/blindEst, y=reorder(State, area), data=circles)

# write.csv(circles, "data/diameters.csv", row.names=FALSE)
```


